ASP_NET_MVC_Learn/OA.UI.Portal/Controllers/UserLoginController.cs
using OA.IBLL;
using OA.UI.Portal.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OA.UI.Portal.Controllers
{
    [LoginCheckFilter(IsCheck =false)]
    //这里用了属性来拒绝Login页面执行过滤器中的用户是否存在的验证
    public class UserLoginController : Controller
    {
        // GET: UserLogin   这地方的注释告诉我们，默认的index()方法是GET请求下的响应

        public IUserInfoService UserInfoService { get; set; }
        public ActionResult Index()
        {
            return View();
        }

        //生成验证码
        public ActionResult ShowVCode()
        {
            string oldcode = Session["ShowVCode"] as string;
            Common.ValidateCode validateCode = new Common.ValidateCode();
            string strCode = validateCode.CreateRandomCode(5);
            Session["VCode"] = strCode;
            return File(validateCode.CreateValidateGraphic(strCode), "image/Jpeg");
        }

        //处理登录的表单
        public ActionResult ProcessLogin()
        {
            //步骤：1. 处理验证码  2.验证用户信息  3.跳转到首页
            //1.
            string strCode = Request["vCode"];      //从前台页面取值  控件的name（vCode）
            string sessionCode = Session["VCode"] as string;        //从session域中取值
            Session["VCode"] = null;
            if (string.IsNullOrEmpty(sessionCode))
            {
                return Content("验证码错误");
            }
            if (strCode!=sessionCode)
            {
                return Content("验证码错误");
            }
            //2.
            string name = Request["loginName"];
            string pwd = Request["loginPwd"];

            short delNormal = (short)Model.Enum.DelFlagEnum.Normal;
            var userinfo_Login = UserInfoService.GetEntities(u => u.UName == name && u.Pwd == pwd && u.DelFlag == delNormal).FirstOrDefault();
            if (userinfo_Login == null)
            {
                return Content("The UserName or Passward Incorrect,Please Login again!");
            }

            //存储登录过的用户信息,用户其他地方的校验
            //Session["loginUser"] = userinfo_Login;

            //注意：早期使用Session来存储用户登录信息，改为 memcache+cookie 来实现
            //(1)使用Guid生成存储数据的key  （2）用户对象信息作为value  （3）将guid存入客户端cookie中
            string userLoginId = Guid.NewGuid().ToString();

            Common.Cache.CacheHelper.AddCache(userLoginId, userinfo_Login, DateTime.Now.AddMinutes(20));


            Response.Cookies["userLoginId"].Value = userLoginId;

            //3.
            //如果验证正确，跳转到首页
            //return Content("Login Success");
            return Redirect("/Home/Index");

        }

    }
}

ASP_NET_MVC_Learn/OA.UI.Portal/Views/UserLogin/Index.cshtml
@{
    ViewBag.Title = "Index";
}


<!DOCTYPE html>

    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Login</title>
        <link rel="stylesheet" type="text/css" href="~/Scripts/CssScripts/Login.css" />

        <script src="~/Scripts/jquery-3.4.1.min.js" type="text/javascript"></script>
        <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
        <script src="~/Scripts/jquery.validate.min.js"></script>

        <!--这里的js代码并没有起作用，我改为后台ProcessLogin方法进行页面跳转-->
        @*<script type="text/javascript">

            $(function () {
                $("#img").click(changeCheckCode);
            });
            function changeCheckCode() {
                var old = $("#img").attr("src");
                var now = new Date();
                var str = old + now.getDay() + now.getHours() + now.getMinutes();
                $("img").attr("src", str);
            }

            function afterLogin(data) {
                if (data == "Login Success") {
                    //登陆成功
                    window.location.href = "/Home/Index";
                } else {
                    alert(data);
                    changeCheckCode();
                }
            }
        </script>*@

    </head>
    <body>
        <!--利用微软的异步提交登录请求-->
        <!--OnSuccess = "afterLogin" -->
        @using (Ajax.BeginForm("ProcessLogin", "UserLogin", new AjaxOptions() { }))
        {
            <div id="login">
                <h1>Login</h1>
                <form method="post">
                    <input type="text" required="required" placeholder="用户名" name="loginName" />
                    <input type="password" required="required" placeholder="密码" name="loginPwd" />
                    <input type="text" required="required" placeholder="验证码" name="vCode" />
                    <img id="img" src="/UserLogin/ShowVCode" onclick="this.src+='?new Date()'" style="float: left;height:24px;" />
                    <button class="but" type="submit">登录</button>
                </form>
            </div>
        }
    </body>
    </html>